### ISSUE TITLE
No internet connection was detected.

### ISSUE THREAD

**Issue by michaelfoxxy** [EidVnex/DMM-Decrypt-Jav-It#1]
Hey EidVnex,

Status is at Initializing for 30 seconds or so. then get a 'No internet connection was detected'.

Using 'DMM Player v2.exe' as DMMPlayer Path.

Happens on open internet connection and/or VPN use.

Let me know if you need more stats

**Comment by michaelfoxxy** [comment]
Hmm, odd it seems to connect - but now says Environment variables 'DMM_USERNAME' or 'DMM_PASSWORD' was not set.

**Comment by EidVnex** [comment]
Hi @michaelfoxxy about the internet connection barely happens sometime. The DMM_USERNAME you need to set on the sytem path if you are on windows.

![image](https://github.com/EidVnex/DMM-Decrypt-Jav-It/assets/170098105/033eb25e-ffa2-43ac-a231-660c63854870)

![image](https://github.com/EidVnex/DMM-Decrypt-Jav-It/assets/170098105/cb0dfd2b-c512-42a3-832c-b44f91c54603)

![image](https://github.com/EidVnex/DMM-Decrypt-Jav-It/assets/170098105/99fbcc1a-cf5a-43e8-8561-f1d6101b7061)
