### ISSUE TITLE
Error obtaining decryption key

### ISSUE THREAD

**Issue by ArkVerdugo** [EidVnex/DMM-Decrypt-Jav-It#2]
Hi,

I'm trying to decrypt a video using DMM Player v2.exe and get an error saying:

"An error occured while trying to obtain your decryption key: Could not reach external secrets provider endpoint."

It says some other things but the text is cut off so I can't read it (and it doesn't appear in the log file).

Is there any way to correct this?

It's possible that this was something fixed in 1.71.1 of jav-it since the latest post on Patreon seems to mention secrets providers.

Thank you in advance for your assistance.

**Comment by ArkVerdugo** [comment]
Hi @EidVnex 

I'm getting the problem with a dcv file. I tried again just now and got the same error but I'll keep trying throughout the day to see if anything changes.

**Comment by EidVnex** [comment]
@ArkVerdugo ok and please let me know the result

**Comment by ArkVerdugo** [comment]
@EidVnex 

I tried a couple more times but it still didn't work. For testing purposes I tried decrypting a VR video and that worked so maybe there's some kind of issue with decrypting non-VR videos?

**Comment by EidVnex** [comment]
@ArkVerdugo Can you run like this by the command prompt and record a video for me? Thanks a lot 

![image](https://github.com/EidVnex/DMM-Decrypt-Jav-It/assets/170098105/c60db32d-c4e2-41b0-8674-1832e26bc4fc)

**Comment by ArkVerdugo** [comment]
@EidVnex 

See below screenshot. I can record a video if you need it. The difference seems to be that the signature is not known for my file. 

![Screenshot 2024-05-31 203738](https://github.com/EidVnex/DMM-Decrypt-Jav-It/assets/149232427/ead094e7-3ce8-4c02-88b0-2a3b459697a7)

**Comment by EidVnex** [comment]
Ok I think I know the problem. I guess the DMM change the decryption key, for this case I think we have to wait the new version

**Comment by ArkVerdugo** [comment]
Ok thanks for your help. Hopefully it can be fixed since it won't let me rip the stream either.

**Comment by EidVnex** [comment]
@ArkVerdugo You can watch this PR, when having new version I will update ASAP. Thanks

**Comment by ArkVerdugo** [comment]
@EidVnex 

Thanks for uploading the new version. I was able to decrypt the video.

**Comment by EidVnex** [comment]
@ArkVerdugo Glad to hear that work for you.
