### ISSUE TITLE
How to solve decrypt error

### ISSUE THREAD

**Issue by 2417254715** [EidVnex/DMM-Decrypt-Jav-It#3]
![decrypt_error](https://github.com/EidVnex/DMM-Decrypt-Jav-It/assets/110730530/764dccac-db48-4e3f-b069-a431ad6109b6)
Is the video encryption updated and the software unusable?

**Comment by yabolan** [comment]
<img width="606" alt="software" src="https://github.com/EidVnex/DMM-Decrypt-Jav-It/assets/157911301/64f77982-a30e-49ca-9ce0-7941cd34ad6c">

Is it only worked for VR video? I tried the HD dcv and shows this.

**Comment by 2417254715** [comment]
> <img alt="software" width="606" src="https://private-user-images.githubusercontent.com/157911301/345352841-64f77982-a30e-49ca-9ce0-7941cd34ad6c.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMTY3NjksIm5iZiI6MTcyMDAxNjQ2OSwicGF0aCI6Ii8xNTc5MTEzMDEvMzQ1MzUyODQxLTY0Zjc3OTgyLWEzMGUtNDljYS05Y2UwLTc5NDFjZDM0YWQ2Yy5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxNDIxMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NjNjMDg4NzdiNGQ2MTRkZmI0ZGQ2NDEwNGE3YThmNWRlNmY5YWJkOWNhZWM0MjRjNWRlODEyZDQ0ZTZmMzkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.S5z7kROU4tKR0V0DTF0QiqLYdJjuzdvLWSLDxaahPLw">
> Is it only worked for VR video? I tried the HD dcv and shows this.

You need to set the windows environment variables in My Computer and create new DMM_USERNAME and DMM_PASSWORD in the system variables.

**Comment by EidVnex** [comment]
![image](https://github.com/EidVnex/DMM-Decrypt-Jav-It/assets/170098105/4314bf0f-934c-4bce-a07d-03c3955e2565)
