### ISSUE TITLE
Decryption Error

### ISSUE THREAD

**Issue by 0122382** [EidVnex/DMM-Decrypt-Jav-It#4]
I set my DMM_USERNAME and DMM_PASSWORD by editing the system environment variables, but still have the partial error "An error occurred while trying to decrypt your video: An error occurred while trying to obtain vault decryption keys: An error occurred while trying to determine"

**Comment by Isopropyl-lab** [comment]
Worked fine for me. Is your username and password _actually_ correct? Also, it was mentioned on certain AV forums that that due to DMM changes, specific videos are currently broken. The next upcoming version should resolve these issues apparently. Stupid DMM always breaks everything!

**Comment by 0122382** [comment]
It works via terminal, not the GUI.
